repos:
  - repo: local
    hooks:
      - id: conventional-commit
        name: conventional commit message
        entry: scripts/check-commit-message
        language: script
        stages: [commit-msg]
